### ISSUE TITLE
MARKET FEEDBACK ERRORS - quick fixes

### ISSUE THREAD

**Issue by dillonhealybtc** [Tribe-BTC/tribe-core#1]
1. Discussed in telegram - hide "request to join" button from any bitpac in the aggregator, only show the button to users that click on the invite link from a creator (DONE)

2. User reports that bitpac is getting created before they click "Create Bitpac" on the creation form just from signing into their wallet. They signed into xverse with half the form filled out and it created the bitpac. see - https://tribebtc.com/tribe?id=bc5a1de9-0eab-43ba-8cac-a04ea739f209

3. Total Bitpacs chart looks like it needs to be reversed 
![Image](https://github.com/Tribe-BTC/tribe-core/assets/70931600/70f5d7d9-7116-4d15-88e2-3343aa9b5383)

4. If the creator clicks out of the module with the invite link, they can't get the invite link back to share. Add the invite link for the creator to the treasury page so they have access to it within the full countdown timeframe.

**Comment by andredevjs** [comment]
@dillonhealybtc ready for review.
